### PR TITLE
Move django_amazon_ses to a single module instead of a deep package

### PR DESCRIPTION
**Pull request by jdufresne**
The django_amazon_ses package was a couple directories deep but only contain a single non-empty file. A single Python file in a package could be more easily represented as a Python module. Makes configuration more concise as well.

### CODE REVIEW

**Comment by jdufresne** [comment]
The Travis failure is being fixed in #21

**Comment by jdufresne** [comment]
Rebased to resolve merge conflicts. Tests are now passing.

**Review by hectcastro — APPROVED** [review]
This appears to be a backwards incompatible change (which I'm fine with). Do you have others planned? Trying to make sure we incorporate that into the decision making process for releases.

If the region variable name changes in https://github.com/azavea/django-amazon-ses/pull/23, that could be a second backwards incompatible change. It would be great to bundle them both into the next backward incompatible release.

**Comment by jdufresne** [comment]
I have no other changes planned. Thanks.

**Comment by hectcastro** [comment]
Looks like this needs to be rebased now, but otherwise, good to merge.

It is a pleasure working with you, @jdufresne.

**Comment by jdufresne** [comment]
The test failures are due to a new html5lib release today. This release causes incompatibilities  with bleach (required by readme_renderer). I've pinned the version as a workaround in PR #25. If that lands, I can rebase this change to verify tests will pass.

**Comment by jdufresne** [comment]
Rebased. Tests are now passing.

**Comment by hectcastro** [comment]
Going to proceed with a 1.0.0 release due to the backward incompatibilities.

**Pull request merged**
