### PR TITLE
Update setup.cfg to support current Django versions

### PR DESCRIPTION
**Pull request by eriknaslund**
Updated the Django dependency to require version 2.2, 3.0 or 3.1, which are the currently supported versions (https://www.djangoproject.com/download/).

### CODE REVIEW

**Comment by hectcastro** [comment]
Thanks for helping keep us up-to-date, @eKIK!

**Comment by eriknaslund** [comment]
> Thanks for helping keep us up-to-date, @eKIK!

Any time! Thanks for django-amazon-ses, and keep up the great work :)

**Comment by nealtodd** [comment]
@hectcastro / @eKIK Thanks for getting django-amazon-ses update to date with Django 3.1.

Are you able to make a 3.0.3 PyPI release so that we can get the Django 3.1 compatible version from there?

**Comment by hectcastro** [comment]
> Are you able to make a 3.0.3 PyPI release so that we can get the Django 3.1 compatible version from there?

Should be good to go. Only difference is that we decided to use 4.0.0 vs. 3.0.3.

**Comment by nealtodd** [comment]
Looks good, thanks for doing that so quickly @hectcastro, much appreciated!

**Pull request merged**
